export const UPDATE_BOOKS = "UPDATE_BOOKS";
export const REMOVE_BOOK = "REMOVE_BOOK";
export const SET_CURRENT_BOOK = "SET_CURRENT_BOOK";
export const ADD_BOOK = "ADD_BOOK";
export const LOADING = "LOADING";

export const ADD_SAVEDBOOK = "ADD_SAVEDBOOK";
export const REMOVE_SAVEDBOOK = "REMOVE_SAVEDBOOK";
export const UPDATE_SAVEDBOOKS = "UPDATE_SAVEDBOOKS";
